version: '3.8'
services:
    01-download :
      build:
        context: ./01-download
      working_dir: /app
      volumes:
        - ./01-download:/app
        - ./data:/app/data
    02-preprocessing:
      build:
        context: ./02-preprocessing
      working_dir: /app
      volumes:
        - ./02-preprocessing:/app
        - ./data:/app/data
      depends_on: 
        - 01-download
    03-training:
      build:
        context: ./03-training
      working_dir: /app
      volumes:
        - ./03-training:/app
        - ./data:/app/data
      depends_on: 
        -  02-preprocessing
    04-prediction:
      build:
        context: ./04-prediction
      working_dir: /app
      ports:
        - 3000:3000
      volumes:
        - ./04-prediction:/app
        - ./data:/app/data
      depends_on: 
        - 03-training